import swaggerAutogenConstructor from 'swagger-autogen';
const swaggerAutogen = swaggerAutogenConstructor();

const doc = {
    info: {
        version: "1.0.0",
        title: "Temizlik Takip Sistemi",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Person:     {
            "id": 10002,
            "name": "Ahmet",
            "lastname": "Yigit",
            "email": "ahmet@gmail.com",
            "password": "12ss12",
            "arrival_date": 15/5/2021,
            "amount_of_work": 8
        },
        Asistan: {
            "id": 10222,
            "name": "Mehmet",
            "lastname": "Yamac",
            "email": "yamac@gmail.com",
            "password": "1234d"
        },
        Admin: {
            "id": 122202,
            "name": "Ibrahim",
            "lastname": "Yanmis",
            "email": "yanis@gmail.com",
            "password": "ss123"
        },    
        Excuse: {
            "id": 12244,
            "excuse_reason": "Okul",
            "start_time": "12:30" ,
            "finish_time": "17:00",
        },
        Task: {
            "id": 34445,
            "place_name": "Salon",
            "time": "12:30" ,
            "explanation": "Yerler Temiylenip camlar silinecek...",
        },
    }
}

const outputFile = './swagger.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})